paths:
  /api/products:
    get:
      summary: Obtenemos todos los productos de la BD
      tags:
        - Products
      responses:
        '200':
          description: Se obtienen todos los productos de la BD correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '404':
          description: No se encontraron productos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor. No se pudieron obtener los productos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/products/mockingproducts:
    get:
      summary: Obtenemos 100 productos falsos creados con faker
      tags:
        - Products
      responses:
        '200':
          description: Se obtienen los 100 los productos falsos con faker correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '401':
          description: No autenticado. Se requiere autenticación para acceder a este recurso.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Prohibido. No tienes permiso para acceder a este recurso.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor. No se pudieron obtener los productos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/products/{pid}:
    get:
      summary: Obtenemos un productos por id de la BD
      tags:
        - Products
      parameters: 
      - name: pid
        in: path
        required: true
        description: id del producto que se quiere obtener de la BD
        schema:
          type: string
      responses:
        '200':
          description: Se obtienen el producto requerido con id de la BD correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '400':
          description: Solicitud incorrecta. Los parámetros de consulta no son válidos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: No se encontró el productos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor. No se pudo obtener el producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Actualizamos un productos por id con un array de la BD
      tags:
        - Products
      parameters: 
      - name: pid
        in: path
        required: true
        description: id del producto que se quiere obtener de la BD
        schema:
          type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        '200':
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '400':
          description: Solicitud incorrecta. Datos inválidos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: No autenticado. Se requiere autenticación.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Prohibido. No tienes permiso para actualizar este producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Producto no encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Eliminamos un productos por id de la BD
      tags:
        - Products
      parameters: 
      - name: pid
        in: path
        required: true
        description: id del producto que se quiere obtener de la BD
        schema:
          type: string
      responses:
        '200':
          description: Producto eliminado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '401':
          description: No autenticado. Se requiere autenticación.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Prohibido. No tienes permiso para eliminar este producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Producto no encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/products/admin:
    post:
      summary: Cargamos un producto como admin a la BD
      tags:
        - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#components/requestBodies/createProduct"
      responses:
        '201':
          description: Producto cargado correctamente como admin
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '400':
          description: Solicitud incorrecta. Datos inválidos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: No autenticado. Se requiere autenticación.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Prohibido. No tienes permiso para crear este producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/products/premium:
    post:
      summary: Cargamos un producto como usuario premium a la BD
      tags:
        - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#components/requestBodies/createProduct"
      responses:
        '201':
          description: Producto cargado correctamente como  premium
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '400':
          description: Solicitud incorrecta. Datos inválidos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: No autenticado. Se requiere autenticación.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Prohibido. No tienes permiso para crear este producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/products/premium/{pid}:
    delete:
      summary: Eliminamos un producto como usuario premium de la BD
      tags:
        - Products
      parameters: 
      - name: pid
        in: path
        required: true
        description: id del producto que se quiere eliminar de la BD
        schema:
          type: string
      responses:
        '200':
          description: Producto eliminado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        '401':
          description: No autenticado. Se requiere autenticación.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Prohibido. No tienes permiso para eliminar este producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Producto no encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    products:
      type: object
      properties: 
        _id: 
          type: ObjectId
          description: Id autogenerado por MongoDB
          require: true
        title: 
          type: string
          description: Titulo del producto
          require: true
        descripcion: 
          type: string
          description: Descripcion del producto
          require: true
        categoria:
          type: string
          description: Categoría a la que pertenece el producto
          require: true
        idCategoria:
          type: number
          description: Id de la categoria a la que pertenece el producto
          require: true
        thumbnail:
          type: array
          description: Array de rutas con las imagenes del producto
          require: false
        price:
          type: number
          description: Precio del producto
          require: true
        onSale:
          type: boolean
          description: boolean para identificar si el producto esta en Sale o Fullprice
          require: true 
        descuento:
          type: number
          description: Valor porcentual de rebaja en caso de que el producto esté en Sale
          require: true
        stock:
          type: number
          description: Stock disponible del producto
          require: true
        alt:
          type: string
          description: alt para las imagenes del producto
          require: false
        status:
          type: boolean
          description: Identificador para saber si el producto está activo o no
          require: true
        code:
          type: string
          description: código único que identifica el producto
          require: true
        owner:
          type: string
          description: Mail del dueño o vendedor del producto
          require: true
      example:
        _id: ObjectId('65b98f0a894980775b28249a')
        title: Biblioteca
        descripcion: Biblioteca de madera blanca con 4 cajones...
        categoria: oficina
        idCategoria: 3
        thumbnail: ['ruta1', 'ruta2']
        price: 1999
        onSale: true
        descuento: 29
        stock: 19
        alt: biblioteca
        status: true
        code: abc004
        owner: admin
    Error: 
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
  requestBodies:
    createProduct:
      type: object
      properties: 
        title: 
          type: string
          description: Titulo del producto
        descripcion: 
          type: string
          description: Descripcion del producto
        categoria:
          type: string
          description: Categoría a la que pertenece el producto
        idCategoria:
          type: number
          description: Id de la categoria a la que pertenece el producto
        thumbnail:
          type: array
          description: Array de rutas con las imagenes del producto
        price:
          type: number
          description: Precio del producto
        onSale:
          type: boolean
          description: boolean para identificar si el producto esta en Sale o Fullprice
        descuento:
          type: number
          description: Valor porcentual de rebaja en caso de que el producto esté en Sale
        stock:
          type: number
          description: Stock disponible del producto
        alt:
          type: string
          description: alt para las imagenes del producto
        status:
          type: boolean
          description: Identificador para saber si el producto está activo o no
        code:
          type: string
          description: código único que identifica el producto
        owner:
          type: string
          description: Mail del dueño o vendedor del producto
      example: 
        title: Biblioteca
        descripcion: Biblioteca de madera blanca con 4 cajones...
        categoria: oficina
        idCategoria: 3
        thumbnail: ['ruta1', 'ruta2']
        price: 1999
        onSale: true
        descuento: 29
        stock: 19
        alt: biblioteca
        status: true
        code: abc004
        owner: admin
    updateProduct:
      type: object
      properties: 
        title: 
          type: string
          description: Titulo del producto actualizado
        descripcion: 
          type: string
          description: Descripcion del producto actualizado
        categoria:
          type: string
          description: Categoría a la que pertenece el producto actualizado
        idCategoria:
          type: number
          description: Id de la categoria a la que pertenece el producto actualizado
        thumbnail:
          type: array
          description: Array de rutas con las imagenes del producto actualizado
        price:
          type: number
          description: Precio del producto actualizado
        onSale:
          type: boolean
          description: boolean para identificar si el producto esta en Sale o Fullprice actualizado
        descuento:
          type: number
          description: Valor porcentual de rebaja en caso de que el producto esté en Sale actualizado
        stock:
          type: number
          description: Stock disponible del producto actualizado
        alt:
          type: string
          description: alt para las imagenes del producto actualizado
        status:
          type: boolean
          description: Identificador para saber si el producto está activo o no, actualizado
        code:
          type: string
          description: código único que identifica el producto actualizado
        owner:
          type: string
          description: Mail del dueño o vendedor del producto actualizado
      example: 
        title: Biblioteca
        descripcion: Biblioteca de madera negra con 5 cajones...
        categoria: oficina
        idCategoria: 3
        thumbnail: ['ruta1', 'ruta2']
        price: 1999
        onSale: true
        descuento: 29
        stock: 19
        alt: biblioteca
        status: true
        code: abc004
        owner: admin
 
